### ISSUE TITLE
Now working

### ISSUE THREAD

**Issue by mjhram** [franznemeth/openwrt-wifi-telegraf#1]
I have openWrt on Raspberry Pi (using the built-in wifi). I installed it using the mentioned steps.
It is not working. No additional measurement is created in influxdb (I am using influxdb as output for telegraf)

**Comment by franznemeth** [comment]
Hi, 
I'm not running openwrt anymore so I cant test if this script is still working. do you have any error message or other output when running this manually?

**Comment by jswclw** [comment]
The issue may be that the exec input is not included in the "std" build of telegraf for OpenWRT. If is, of course, part of the "full" build, but I cannot run that myself. It installs but completely maxes out my router's storage.

Speaking for myself, it would be nice to see the "exec" input included in the std/normal/small telegraf package!
